disabled_rules:
 - closing_brace
 - class_delegate_protocol
 - closure_parameter_position #ERROR
 - colon
 - comma
 - compiler_protocol_init
 - control_statement
 - custom_rules
 - cyclomatic_complexity
 - dynamic_inline
 - empty_parameters
 - empty_parentheses_with_trailing_closure
 - file_length
 - force_cast
 - force_try
 - function_body_length
 - function_parameter_count
 - generic_type_name
 - implicit_getter
 - large_tuple
 - leading_whitespace
 - legacy_cggeometry_functions
 - legacy_constant
 - legacy_constructor
 - legacy_nsgeometry_functions
 - line_length
 - mark
 - nesting
 - opening_brace
 - operator_whitespace
 - private_unit_test
 - redundant_optional_initialization
 - redundant_string_enum_value
 - redundant_void_return
 - return_arrow_whitespace
 - shorthand_operator #ERROR
 - statement_position
 - syntactic_sugar
 - todo
 - trailing_comma #ERROR
 - trailing_newline
 - trailing_semicolon
 - trailing_whitespace
 - type_body_length
 - type_name
 - unused_closure_parameter
 - unused_enumerated
 - unused_optional_binding
 - valid_docs
 - valid_ibinspectable
 - variable_name
 - vertical_parameter_alignment
 - vertical_whitespace
 - void_return
 - weak_delegate

opt_in_rules:
 # - attributes
 # - closure_end_indentation
 # - closure_spacing
 # - conditional_returns_on_newline
#  - empty_count
#  - explicit_init
#  - file_header
#  - first_where
#  - force_unwrapping
#  - missing_docs
#  - nimble_operator
#  - number_separator
#  - object_literal
  # - operator_usage_whitespace
#  - overridden_super_call
#  - private_outlet
#  - prohibited_super_call
#  - redundant_nil_coalescing
#  - sorted_imports
#  - switch_case_on_newline

included:
  - Triplan/

excluded:
  - Triplan/external
  - Triplan/Assets.xcassets
  - Pods


line_length: 200
type_name: 
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded: _

