disabled_rules:
 # - closing_brace
 # - colon
 # - comma
 # - control_statement
 # - custom_rules
 # - cyclomatic_complexity
 # - file_length
  - force_cast
 # - force_try
 # - function_body_length
 # - function_parameter_count
 # - implicit_getter
 # - leading_whitespace
 # - legacy_cggeometry_functions
 # - legacy_constant
 # - legacy_constructor
 # - legacy_nsgeometry_functions
 # - line_length
 # - mark
 # - nesting
 # - opening_brace
 # - operator_whitespace
 # - private_unit_test
 # - return_arrow_whitespace
 # - statement_position
 # - syntactic_sugar
 # - todo
 # - trailing_comma
 # - trailing_newline
 # - trailing_semicolon
 # - trailing_whitespace
 # - type_body_length
  - type_name
 # - valid_docs
 # - valid_ibinspectable
  - variable_name
 # - vertical_whitespace
 # - weak_delegate

opt_in_rules:
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - explicit_init
  - force_unwrapping
  - missing_docs
  - nimble_operator
  - overridden_super_call
  - private_outlet
  - redundant_nil_coalescing
  - switch_case_on_newline

included:
  - Triplan/

excluded:
  - Triplan/external
  - Triplan/Assets.xcassets
  - Pods


line_length: 200
type_name: 
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded: _

