whitelist_rules:

# 상시 활성화 (자동)
  - attributes # opt-in
  - class_delegate_protocol
  - closing_brace
#  - closure_end_indentation # opt-in #ERROR
#  - closure_parameter_position #ERROR
  - closure_spacing # opt-in
  - colon
  - comma
  - compiler_protocol_init
  - conditional_returns_on_newline # opt-in
  - control_statement
  - cyclomatic_complexity # opt-in
  - dynamic_inline
  - empty_count # opt-in
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_init # opt-in
  - file_length
#  - first_where # opt-in #ERROR
  - force_cast
  - force_try
  - force_unwrapping # opt-in
  - function_body_length
  - function_parameter_count
  - generic_type_name
  - implicit_getter
  - large_tuple
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - line_length
  - mark
  - nesting
  - number_separator # opt-in
  - object_literal # opt-in
  - opening_brace
  - operator_usage_whitespace # opt-in
  - operator_whitespace
  - overridden_super_call # opt-in
  - private_unit_test
  - prohibited_super_call # opt-in
  - redundant_nil_coalescing # opt-in
  - redundant_optional_initialization
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
#  - shorthand_operator #ERROR
  - statement_position
  - switch_case_on_newline # opt-in
  - syntactic_sugar
#  - trailing_comma #ERROR
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - unused_closure_parameter
  - unused_enumerated
  - unused_optional_binding
  - valid_docs
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_whitespace
  - void_return
  - weak_delegate

included:
  - Triplan/

excluded:
  - Triplan/external
  - Triplan/Assets.xcassets
  - Pods

line_length: 200
type_name: 
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded: _

